### ISSUE TITLE
CSS issue: skeleton-shine unsupported background-position property on PageSpeed

### ISSUE THREAD

**Issue by vuquangpham** [viivue/atomic-css#19]
The problem occurs when we test the page speed on https://pagespeed.web.dev/

I think it causes a bug because of the conflict between using `background-position` in `animation`.

![image](https://user-images.githubusercontent.com/30406982/229764747-046bfdbb-a127-4a8a-a27b-5be045f7a3d8.png)

**Comment by phucbm** [comment]
Fix with https://github.com/viivue/atomic-css/releases/tag/v1.1.8
